[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_coinflip_game = "64CRrSCxSoEUDv2Sg3fKrwxotoiyD1bfce1AyCeuF582"
[programs.devnet]
solana_coinflip_game = "64CRrSCxSoEUDv2Sg3fKrwxotoiyD1bfce1AyCeuF582"

   [toolchain]
        anchor_version = "0.29.0"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/ddm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
